BASE_URL = 'https://www.rocketfinancial.com'
DIRECTORY = 'Financials.aspx'

COMPANY_FID = 'fID'
COMPANY_PW = 'pw'

TIME_SPAN = 'p'
REPORT_TYPE = 'tID'
STAT_TYPE = 'stID'

TIME_ANNUAL = 2
TIME_QUARTERLY = 1
TIME_TTM = 3

REPORT_STANDARDIZED = 1
REPORT_AS_REPORTED = 2

STAT_BUSINESS = 1
STAT_PRODUCT = 3
STAT_GEOGRAPHIC = 2

PAGE_KEY = 'i'
PAGE_COUNT = 8
PAGE_TOTAL_QUARTERLY = 80 #20 years
PAGE_TOTAL_YEARLY = 20
PAGE_TOTAL_TTM = 320
